/* Commission content uses the existing Adoptable Firebase project, in its own collections. */
(()=>{
const config={apiKey:'AIzaSyCGuowjScRtT3Xi451MIy_cfDRoFxwFIkg',authDomain:'akane-adoptshop.firebaseapp.com',projectId:'akane-adoptshop',storageBucket:'akane-adoptshop.firebasestorage.app',messagingSenderId:'431915875227',appId:'1:431915875227:web:80ed5ed2788b88f56abf3e'};
const app=firebase.apps.length?firebase.app():firebase.initializeApp(config),db=app.firestore();
const current=db.collection('commissionSite').doc('current');
const mediaCache=new Map();let revision=null,saving=false,queue=Promise.resolve(),unsubscribe;
function errorMessage(error){return error.code==='permission-denied'?'Firebase ไม่อนุญาตให้บันทึกข้อมูลค่ะ':error.code==='unavailable'?'เชื่อมต่อ Firebase ไม่ได้ กรุณาตรวจอินเทอร์เน็ตแล้วลองอีกครั้งค่ะ':error.message||'บันทึกไม่สำเร็จ กรุณาลองอีกครั้งค่ะ';}
async function parallel(items,fn){const result=new Array(items.length);let next=0;await Promise.all(Array.from({length:Math.min(6,items.length)},async()=>{while(next<items.length){const i=next++;result[i]=await fn(items[i],i);}}));return result;}
async function digest(value){const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('');}
async function storeMedia(data){const id=await digest(data),ref=db.collection('commissionMedia').doc(id);if(!mediaCache.has(id)){const exists=await ref.get();if(!exists.exists){const pieces=data.match(/[\s\S]{1,600000}/g)||[];await parallel(pieces,(text,i)=>ref.collection('parts').doc(String(i)).set({text}));await ref.set({count:pieces.length,createdAt:firebase.firestore.FieldValue.serverTimestamp()});}mediaCache.set(id,data);}return 'akane-media:'+id;}
async function loadMedia(id){if(mediaCache.has(id))return mediaCache.get(id);const ref=db.collection('commissionMedia').doc(id),doc=await ref.get();if(!doc.exists)throw new Error('ไม่พบไฟล์ภาพที่บันทึกไว้');const parts=await parallel(Array.from({length:doc.data().count},(_,i)=>i),async i=>{const part=await ref.collection('parts').doc(String(i)).get();if(!part.exists)throw new Error('โหลดไฟล์ภาพไม่ครบ กรุณาลองอีกครั้ง');return part.data().text;});const data=parts.join('');mediaCache.set(id,data);return data;}
async function transform(value,upload){if(typeof value==='string'){if(upload&&/^data:(image|video)\//.test(value))return storeMedia(value);if(!upload&&value.startsWith('akane-media:'))return loadMedia(value.slice(12));return value;}if(Array.isArray(value))return parallel(value,v=>transform(v,upload));if(value&&typeof value==='object'){const pairs=await parallel(Object.entries(value),async([key,v])=>[key,await transform(v,upload)]);return Object.fromEntries(pairs);}return value;}
async function read(doc){if(!doc.exists){revision=null;return null;}const meta=doc.data(),ref=db.collection('commissionRevisions').doc(meta.revision);const parts=await parallel(Array.from({length:meta.count},(_,i)=>i),async i=>{const part=await ref.collection('parts').doc(String(i)).get();if(!part.exists)throw new Error('โหลดข้อมูลไม่ครบ กรุณารีเฟรช');return part.data().text;});const data=await transform(JSON.parse(parts.join('')),false);revision=meta.revision;return data;}
async function save(data){const snapshot=JSON.parse(JSON.stringify(data));const job=queue.then(async()=>{saving=true;try{const expected=revision,encoded=JSON.stringify(await transform(snapshot,true)),pieces=encoded.match(/[\s\S]{1,180000}/g)||[],id=crypto.randomUUID(),ref=db.collection('commissionRevisions').doc(id);await parallel(pieces,(text,i)=>ref.collection('parts').doc(String(i)).set({text}));await db.runTransaction(async tx=>{const doc=await tx.get(current);if(doc.exists&&doc.data().revision===id)return;if((doc.exists?doc.data().revision:null)!==expected)throw new Error('มีการแก้ไขจากอีกหน้า กรุณารีเฟรชเพื่อรับข้อมูลล่าสุดก่อนบันทึกค่ะ');tx.set(current,{revision:id,count:pieces.length,updatedAt:firebase.firestore.FieldValue.serverTimestamp()});});revision=id;return true;}finally{saving=false;}});queue=job.catch(()=>{});return job;}
window.AkaneCloud={load:async()=>read(await current.get()),save,errorMessage,subscribe(onData,onError){unsubscribe?.();unsubscribe=current.onSnapshot(async doc=>{if(saving||!doc.exists||doc.data().revision===revision)return;try{onData(await read(doc));}catch(error){onError?.(errorMessage(error));}},error=>onError?.(errorMessage(error)));return ()=>unsubscribe?.();}};
})();
